name: Auto Publish Package on Merge to Main

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '--skip-ci') == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      #   - name: Run tests // currently disable test, until check all test cases
      #     run: npm test

      - name: Build packages
        run: npm run build

      - name: Login to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish --access public
